# Generated by Django 5.1.1 on 2024-11-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Отображать на сайте'),
        ),
    ]
