# Generated by Django 5.1.1 on 2024-11-09 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_period_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Животное', 'verbose_name_plural': 'Животные'},
        ),
        migrations.AlterModelOptions(
            name='bid',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'verbose_name': 'Период', 'verbose_name_plural': 'Периоды'},
        ),
        migrations.RemoveField(
            model_name='animal',
            name='period',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='animals',
        ),
        migrations.RemoveField(
            model_name='period',
            name='found_quantity',
        ),
        migrations.AddField(
            model_name='bid',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сессия пользователя'),
        ),
        migrations.AddField(
            model_name='period',
            name='animals',
            field=models.ManyToManyField(to='app.animal', verbose_name='Животные'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='group',
            field=models.CharField(max_length=255, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='quantity_found',
            field=models.IntegerField(verbose_name='Количество найденных окаменелостей особи'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.period', verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
