# Generated by Django 5.1.1 on 2024-11-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_animal_options_alter_bid_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='period',
        ),
        migrations.AddField(
            model_name='bid',
            name='period',
            field=models.ManyToManyField(to='app.period', verbose_name='Период'),
        ),
    ]
