# Generated by Django 5.1.1 on 2024-11-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_bid_period_bid_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('ON_DELETE', 'Удален'), ('APPROVED', 'Сформирована'), ('FINISHED', 'Завершен'), ('REJECTED', 'Отклонён')], default='DRAFT', max_length=15, verbose_name='Статус'),
        ),
    ]
