# Generated by Django 5.1.1 on 2024-11-24 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_bid_created_at_bid_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='period',
        ),
        migrations.AddField(
            model_name='bid',
            name='comment',
            field=models.TextField(default=1, verbose_name='Комментарий к модератору'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BidPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Количесвто')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='app.bid', verbose_name='Заявка')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='app.bid', verbose_name='Период')),
            ],
            options={
                'verbose_name': 'M2M',
                'verbose_name_plural': 'M2M',
                'unique_together': {('bid', 'period')},
            },
        ),
    ]
