# Generated by Django 5.1.1 on 2024-11-24 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_bidperiod_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidperiod',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='app.period', verbose_name='Период'),
        ),
    ]
