# Generated by Django 5.1.1 on 2024-11-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_bidperiod_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='finished_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AddField(
            model_name='bid',
            name='to_form_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования'),
        ),
    ]
