# Generated by Django 5.1.1 on 2024-12-15 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_bid_finished_at_bid_to_form_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.animal', verbose_name='Животное'),
        ),
    ]
