# Generated by Django 5.1.1 on 2024-12-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_bid_animal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidperiod',
            name='count',
        ),
        migrations.AddField(
            model_name='bidperiod',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий'),
        ),
    ]
