# Generated by Django 5.1.1 on 2024-12-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_bidperiod_count_bidperiod_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
    ]
