# Generated by Django 5.1.1 on 2025-01-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_bid_finished_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidperiod',
            name='comment',
        ),
        migrations.AddField(
            model_name='bidperiod',
            name='quantity_found',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество найденных окаменелостей особи'),
        ),
    ]
