# Generated by Django 5.1.1 on 2025-01-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_bidperiod_comment_bidperiod_quantity_found'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidperiod',
            name='quantity_found',
            field=models.IntegerField(default=1, verbose_name='Количество найденных окаменелостей особи'),
        ),
    ]
