# Generated by Django 5.1.2 on 2025-01-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_bidperiod_quantity_found'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='qr',
            field=models.TextField(blank=True, null=True, verbose_name='QR код'),
        ),
    ]
